### ISSUE TITLE
Rotirea

### ISSUE THREAD

**Issue by Thomas1995** [rosedu/problema-cdl-2016#1]
> Coordonatele pătratului după rotire vor fi (0, -2), (2, -2), (-2, 0) și (0, 0)

Ar trebui sa fie (0, -2), (**-2**, -2), (-2, 0) și (0, 0).

**Comment by palcu** [comment]
Nu cred.

![img_20160308_103207](https://cloud.githubusercontent.com/assets/772220/13596140/1fc11cf4-e519-11e5-89a4-ff8648c29f64.jpg)

**Comment by Thomas1995** [comment]
> Coordonatele pătratului după rotire vor fi (0, -2), (2, -2), (-2, 0) și (0, 0). (rotirea se face după operația de translație de mai sus)

Dar dupa operatia de translatie, avem:

> Dacă considerăm pătratul de mai sus, coordonatele vârfurilor vor fi (-2, 0), (-2, 2), (0, 2) şi (0, 0).

Primul desen are coordonatele (0, 0), (2, 0), (0, 2), (2, 2) (cele initiale).

Iar al doilea desen are coordonatele (0, 0), (0, 2), (-2, 0), (-2, 2), in timp ce in exemplul de dupa rotire spune ca acestea sunt: (0, -2), (2, -2), (-2, 0), (0, 0), insa acestea nu alcatuiesc un patrat.

**Comment by dumytru** [comment]
Dap, ai dreptate.
Coordonatele sunt (0, -2), (-2, -2), (-2, 0), (0, 0) după rotire. Am tastat eu greșit, scuze.
