### ISSUE TITLE
intersectie

### ISSUE THREAD

**Issue by ovidiunitu** [rosedu/problema-cdl-2016#10]
Suprapunerea a doua figuri implica si intersectia lor? De exemplu: patratul de latura 3 ce are coltul stanga jos in punctul (0,0), se intersecteaza cu patratul de latura 1 cu coltul stanga jos in punctul (1,1)?

**Comment by palcu** [comment]
Dap.

https://github.com/rosedu/problema-cdl-2016/issues/3

**Comment by ovidiunitu** [comment]
Merci, nu am citit cu atentie si celalate intrebari.
