### ISSUE TITLE
Poligon - puncte coliniare

### ISSUE THREAD

**Issue by ioanachirca** [rosedu/problema-cdl-2016#11]
Un poligon cu punctele coliniare (cum este exemplul "Vreau un poligon cu punctele (1,1), (3,3), (4,4).") este considerat valid si memorat, sau este ignorat?

**Comment by palcu** [comment]
Bună întrebare.

În geometria euclidiană clasică, o dreaptă nu este considerată [poligon](https://en.wikipedia.org/wiki/Polygon#Naming_polygons).

Dar dat fiind situația noastră mai _specială_, am decis ca un segment de dreaptă să fie considerat un _poligon convex_, dar un singur punct nu este.

**Comment by AlexandraM-C** [comment]
Se poate sa primim o comanda de creare poligon cu un singur punct? Si atunci ar trebui ignorata comanda?

**Comment by palcu** [comment]
Nu se va primi o comanda cu un singur punct. Și nici o comanda cu mai multe
puncte, care sunt aceleași.
