### ISSUE TITLE
Conditie cuvant cheie

### ISSUE THREAD

**Issue by DanIulian** [rosedu/problema-cdl-2016#12]
Daca avem un vers ce contine un cuvant cheie, ni se garanteaza ca acesta este cuvantul initial gen "Vreau un patrat de latura 2 in (2,3), sau de exemplu putem avea si "Si o sa vreau un patrat de latura 2 in (2,3)" ? 
Multumesc frumos.

**Comment by palcu** [comment]
Da, se garantează. Formatul pentru versurile cu cuvinte cheie este fix.

**Comment by vladeugeniu** [comment]
Deci.. cuvintele cheie pot aparea in alte propozitii? 
Pot aparea variante  " Vreau un  afara ploua patrat în punctul (0,0) de latura 2."  pe care sa le ignoram sau alte variatii de genul acesta cum ar fi mai multe numere la final?

**Comment by palcu** [comment]
Nu vor apărea variații în versurile cu cuvinte cheie, în afară de linia cu `Gata`.

**Comment by vladeugeniu** [comment]
Pai, orice vers care incepe cu Gata, dupa intrarea in blocul decizional, il va incheia?

**Comment by palcu** [comment]
Da, dar după cuvântul cheie `Gata`, poate urma orice pe acea linie. E singura instrucțiune care nu are un format chiar fix.

**Comment by ioanachirca** [comment]
Cuvintele cheie pot aparea in propozitiile fara comenzi? ex. "Vreau sa vii in codru la izvor"

**Comment by palcu** [comment]
Nu.
