### ISSUE TITLE
Poligoane particulare

### ISSUE THREAD

**Issue by dosarudaniel** [rosedu/problema-cdl-2016#13]
Comanda:
_Vreau un poligon cu punctele (0,1), (1,4),  (4,3),  (3,0)._
Va creea un poligon ce va fi afişat mai apoi ca Pătrat sau ca Poligon?

**Comment by dumytru** [comment]
Poligon. Orice comandă de care conține `poligon` va creea un poligon, chiar dacă forma e de pătrat.

**Comment by dosarudaniel** [comment]
Bănuiesc că afirmaţia:

> se garantează că toate punctele poligoanelor vor fi în intervalul INT_MIN, INT_MAX, indiferent de ce mișcări vor fi făcute pe planul geometric

este valabilă şi pentru pătrate, cât şi pentru dreptunghiuri, nu?

**Comment by palcu** [comment]
Da.
