### ISSUE TITLE
Aplicare operatii si executabil

### ISSUE THREAD

**Issue by razvancurcudel** [rosedu/problema-cdl-2016#19]
1. se garanteaza ca forma pe care se executa o operatie de stergere/mutare/rotire etc exista ? sau trebuie facute verificari in acest sens ?
2. cum trebuie sa se numeasca executabilul (clasa main) rezultatat in urma compilarii programului Java ?

**Comment by dosarudaniel** [comment]
În completarea primei întrebări, se garantează că există şi nu a fost ştearsă?

**Comment by dumytru** [comment]
1. Se garantează.
2. Nu există restricții pentru numele executabilului, important e să primească doi parametri în linia de comandă.
