### ISSUE TITLE
Rezultat exemplu de poezie

### ISSUE THREAD

**Issue by Thomas1995** [rosedu/problema-cdl-2016#2]
Rezultatul in urma parsarii spune ca este:

> 0 Patrat:
> 0 0
> 0 2
> 2 0
> 2 2
> 1 Dreptunghi:
> 1 1
> 1 3
> 4 1
> 4 3
> 2 Poligon:
> 1 1
> 3 3
> 4 4

Dar acesta nu tine cont de:

> Muta in stanga figura 0 cu 2.
> Roteste figura 1 cu 90 de grade la punctul (1,1).

Corect nu ar fi asa?

> 0 Patrat:
> -2 0
> -2 2
> 0 0
> 0 2
> 1 Dreptunghi:
> -1 -1
> -1 2
> 1 -1
> 1 2
> 2 Poligon:
> 1 1
> 3 3
> 4 4

**Comment by dumytru** [comment]
După primul issue scris de tine mi-am dat seama ca si exemplul e greșit și el. Am să-l pun pe cel corect cat de curând.

Mersi și scuze.

**Comment by dumytru** [comment]
Am rulat din nou programul si am si verificat de mana (pentru ca nu corespundea cu ce ai scris tu mai sus).

Output-ul ar trebui sa fie urmatorul:

```
0 Patrat:
-2 0
-2 2
0 0
0 2
1 Dreptunghi:
-1 4
-1 1
1 1
1 4
2 Poligon:
1 1
3 3
4 4
```

**Comment by Thomas1995** [comment]
Da, asa e, scuze, pusesem alta origine la dreptunghi. Asa imi da si mie.

**Comment by Thomas1995** [comment]
> După ce parsați întreaga poezie, va trebui la final să afișați pentru toate figurile din ea, toate punctele în care se află. Punctele vor fi sortate după X și apoi după Y.

@dumytru Acum mi-am dat seama, trebuie inversate primele 2 puncte de la dreptunghi:

> 1 Dreptunghi:
> **-1 1
> -1 4**
> 1 1
> 1 4

**Comment by dumytru** [comment]
&#x1f44d;
