### ISSUE TITLE
Semne de punctuatie

### ISSUE THREAD

**Issue by DanIulian** [rosedu/problema-cdl-2016#20]
Ce semne de punctuatie putem intalni in poezie? In afara de "." si "," ?

**Comment by Julian-Dumitrascu** [comment]
1. Cred că putem să folosim orice puncte de punctuație. Exemple:
1.1 punct și virgulă ;
1.2 semnul exclamării !
1.3 semnul întrebării ?
1.4 puncte de suspensie ...
1.5 cratimă -
1.6 paranteze ()
2. Putem să comunicăm mai mult despre [literatură](https://github.com/Julian-Dumitrascu/comunicare/issues/1).
