### ISSUE TITLE
Intrebare: Intersectie

### ISSUE THREAD

**Issue by Thomas1995** [rosedu/problema-cdl-2016#3]
Intersectia a doua figuri inseamna daca se intersecteaza laturile sau si interiorul?
De exemplu daca am un patrat strict in interiorul unui alt patrat, ele se intersecteaza?

**Comment by dumytru** [comment]
> Intersectia a doua figuri inseamna daca se intersecteaza laturile sau si interiorul?

Două figuri se intersectează dacă se suprapun în cel puțin un punct din plan.

> De exemplu daca am un patrat strict in interiorul unui alt patrat, ele se intersecteaza?

Da, se intersectează.

**Comment by Thomas1995** [comment]
Se intersecteaza inclusiv daca au doar un colt comun, nu?

**Comment by dumytru** [comment]
Da.
