### ISSUE TITLE
Diacritice

### ISSUE THREAD

**Issue by dosarudaniel** [rosedu/problema-cdl-2016#5]

**Comment by palcu** [comment]
Nu m-am prins de ce ai deschis enunțul și apoi l-ai închis, dar îți răspund la întrebare că poate fi de interes pentru toată lumea.

> Salut,
> 
> În enunțul problemei cuvintele cheie sunt fără diacritice. Însă în exemple, unele din cuvintele cheie conțin diacritice. Vom ține cont de acest lucru? E necesar ca programul să funcționeze atât pentru teste ce conțin cuvinte cheie cu diacritice sau e suficient ca programul să funcționeze pentru teste ce conțin doar cuvinte cheie fără diacritice, așa cum sunt în enunț?
> 
> Mulțumesc!

În fișierul de intrare vor fi doar caractere ASCII.

**Comment by palcu** [comment]
Am șters toate diacriticile din _bucățile de cod_ din enunț ca să nu mai existe confuzii.

_Sper doar să nu fim dați exemplu pe [diacritica](https://diacritica.wordpress.com/category/nelinisti-ortografice/)._ :fearful:

**Comment by dosarudaniel** [comment]
Salut,
Scuzele mele. Am recitit apoi enunţul şi am observat că era menţionat că în fişierul de intrare nu vor fi diacritice.
Mulţumesc! 

```
On Wednesday, March 9, 2016 1:12 PM, Alex Palcuie <notifications@github.com> wrote:
```

 Nu m-am prins de ce ai deschis enunțul și apoi l-ai închis, dar îți răspund la întrebare că poate fi de interes pentru toată lumea.
Salut,În enunțul problemei cuvintele cheie sunt fără diacritice. Însă în exemple, unele din cuvintele cheie conțin diacritice. Vom ține cont de acest lucru? E necesar ca programul să funcționeze atât pentru teste ce conțin cuvinte cheie cu diacritice sau e suficient ca programul să funcționeze pentru teste ce conțin doar cuvinte cheie fără diacritice, așa cum sunt în enunț?Mulțumesc!
În fișierul de intrare vor fi doar caractere ASCII.—
