### ISSUE TITLE
Intrebare: Creare de obiecte 2D

### ISSUE THREAD

**Issue by minescoviciu** [rosedu/problema-cdl-2016#6]
Daca ni se da un punct si lungimea laturii patratului o sa avem 4 cazuri de a considera colturile patratului. De exemplu, pentru "Vreau un patrat în punctul (0,0) de latura 2." vom avea urmatoarele patrate posibile:
varrianta 1
0 0
0 2
2 2
2 0
varianta 2
0 0
0 2
-2 2
-2 0
varianta 3
0 0
0 -2
-2 -2
-2 0
varianta 4
0 0
0 -2
2 -2
2 0
Cum le cream?

**Comment by Thomas1995** [comment]
> Cuvântul cheie pentru comanda de creare este vreau. Versul de mai jos crează un pătrat de latură 2. Punctul (0, 0) din comandă corespunde **colțului din stanga-jos** a patratului

**Comment by minescoviciu** [comment]
Multumesc!
