### ISSUE TITLE
Ordinea punctelor la formarea poligoanelor

### ISSUE THREAD

**Issue by cristiannancu** [rosedu/problema-cdl-2016#7]
Se poate considera ca oricare 2 puncte date consecutiv la creare formeaza o latura a poligonului sau punctele sunt date aleator?

**Comment by cristiannancu** [comment]
@palcu ?

**Comment by dumytru** [comment]
Exact așa cum zice în enunț, se dă lista punctelor din care e format poligonul; singura condiție e ca poligonul să fie convex. 
E parte din problemă să-ți dai seama dacă ordinea în care se dau punctele contează, dar ca să-ți răspund la întrebare:
- dacă aceiași mulțime de puncte poate descrie două poligoane convexe diferite, atunci ordinea contează
- dacă, indiferent de ordine, o mulțime de puncte descrie un singur poligon convex, atunci ordinea nu contează.

**Comment by AlexandraM-C** [comment]
Se poate ca o linie ce conține „vreau” să ceara crearea mai multor poligoane? Si atunci în loc de „vreau un” ar fi „vreau doua/trei/etc.” ?

**Comment by dumytru** [comment]
Nu. Se creează o singură figură per comandă.

**Comment by dosarudaniel** [comment]
Deci comenzile:

_Vreau un poligon cu punctele (1,1), (0,4), (3,5), (5,3), (4,0).
Vreau un poligon cu punctele (1,1), (3,5), (0,4), (5,3), (4,0)._

Vor creea aceeaşi figură, nu?

**Comment by palcu** [comment]
Vor fi două poligoane separate (unul cu id 0 și altul cu id 1), dar ele vor avea aceleași coordonate.
