### ISSUE TITLE
Structura de decizie

### ISSUE THREAD

**Issue by AndreeaNicolescu** [rosedu/problema-cdl-2016#8]
Este posibil sa avem o structura de decizie in interiorul alteia ? 
Ce vrea sa spuna fraza "Este valid să se trimită același ID (și e evident că cele două obiecte se vor intersecta)."? Cum pot trimite acelasi ID daca verific de exemplu ca figurile 0 si 1, cu id-uri diferite se intersecteaza?

**Comment by palcu** [comment]
> Este posibil sa avem o structura de decizie in interiorul alteia ? 

Da, se poate.

> Ce vrea sa spuna fraza "Este valid să se trimită același ID (și e evident că cele două obiecte se vor intersecta)."? 

De exemplu:

`Daca figura 1 intersecteaza figura 1.`
