### ISSUE TITLE
Linia ce conține „gata”

### ISSUE THREAD

**Issue by AlexandraM-C** [rosedu/problema-cdl-2016#9]
> Linia care contine comanda gata nu are un format fix; linia va incepe mereu cu gata, dar dupa se poate continua un vers normal 

Un vers „normal” e un vers fără vreo instrucțiune/cuvât cheie? Adică nu putem avea o altă instrucțiune pe aceeași linie cu „gata”?

**Comment by palcu** [comment]
Nu, nu va fi niciun alt cuvânt cheie pe aceiași linie cu `Gata`.

**Comment by AlexandraM-C** [comment]
Mulțumesc frumos :)
